import type { AlgorithmDef } from './caseTable.ts'

/*
 * Algorithm lists. Only the algorithms live here; the patterns they solve
 * are generated by buildCaseTable. To add a case (for example a full OLL
 * set), add a line. The tests check that the lists cover every last-layer
 * state and that no two entries solve the same case.
 *
 * Algorithms may contain rotations (x y z) and wide/slice moves. A net
 * rotation at the end is undone automatically.
 */

/** 2-look OLL, step 1: orient the edges (make the cross). */
export const OLL_2LOOK_EDGES: readonly AlgorithmDef[] = [
  { name: 'Line', alg: "F R U R' U' F'" },
  { name: 'L-shape', alg: "f R U R' U' f'" },
  { name: 'Dot', alg: "F R U R' U' F' f R U R' U' f'" },
]

/** 2-look OLL, step 2: orient the corners (edges already oriented). */
export const OLL_2LOOK_CORNERS: readonly AlgorithmDef[] = [
  { name: 'Sune', alg: "R U R' U R U2 R'" },
  { name: 'Antisune', alg: "R U2 R' U' R U' R'" },
  { name: 'H', alg: "R U R' U R U' R' U R U2 R'" },
  { name: 'Pi', alg: "R U2 R2 U' R2 U' R2 U2 R" },
  { name: 'Headlights', alg: "R2 D R' U2 R D' R' U2 R'" },
  { name: 'T', alg: "r U R' U' r' F R F'" },
  { name: 'Bowtie', alg: "F' r U R' U' r' F R" },
]

/** 2-look PLL, step 1: permute the corners. */
export const PLL_2LOOK_CORNERS: readonly AlgorithmDef[] = [
  { name: 'Headlights (T-perm)', alg: "R U R' U' R' F R2 U' R' U' R U R' F'" },
  { name: 'Diagonal (Y-perm)', alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
]

/** 2-look PLL, step 2: permute the edges (corners already solved). */
export const PLL_2LOOK_EDGES: readonly AlgorithmDef[] = [
  { name: 'Ua', alg: "M2 U M U2 M' U M2" },
  { name: 'Ub', alg: "M2 U' M U2 M' U' M2" },
  { name: 'H', alg: 'M2 U M2 U2 M2 U M2' },
  { name: 'Z', alg: "M' U M2 U M2 U M' U2 M2" },
]

/** Full PLL: all 21 cases. */
export const PLL_FULL: readonly AlgorithmDef[] = [
  { name: 'Aa', alg: "x R' U R' D2 R U' R' D2 R2 x'" },
  { name: 'Ab', alg: "x R2 D2 R U R' D2 R U' R x'" },
  { name: 'E', alg: "x' R U' R' D R U R' D' R U R' D R U' R' D' x" },
  { name: 'F', alg: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R" },
  { name: 'Ga', alg: "R2 U R' U R' U' R U' R2 U' D R' U R D'" },
  { name: 'Gb', alg: "R' U' R U D' R2 U R' U R U' R U' R2 D" },
  { name: 'Gc', alg: "R2 U' R U' R U R' U R2 U D' R U' R' D" },
  { name: 'Gd', alg: "R U R' U' D R2 U' R U' R' U R' U R2 D'" },
  { name: 'H', alg: 'M2 U M2 U2 M2 U M2' },
  { name: 'Ja', alg: "x R2 F R F' R U2 r' U r U2 x'" },
  { name: 'Jb', alg: "R U R' F' R U R' U' R' F R2 U' R'" },
  { name: 'Na', alg: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'" },
  { name: 'Nb', alg: "R' U R U' R' F' U' F R U R' F R' F' R U' R" },
  { name: 'Ra', alg: "R U' R' U' R U R D R' U' R D' R' U2 R'" },
  { name: 'Rb', alg: "R2 F R U R U' R' F' R U2 R' U2 R" },
  { name: 'T', alg: "R U R' U' R' F R2 U' R' U' R U R' F'" },
  { name: 'Ua', alg: "M2 U M U2 M' U M2" },
  { name: 'Ub', alg: "M2 U' M U2 M' U' M2" },
  { name: 'V', alg: "R' U R' U' y R' F' R2 U' R' U R' F R F" },
  { name: 'Y', alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
  { name: 'Z', alg: "M' U M2 U M2 U M' U2 M2" },
]

/**
 * Full OLL: all 57 cases in one algorithm. Names follow the standard
 * numbering with the usual shape group. The numbers are labels only; the
 * tests prove the set is complete and has no duplicates, but can't prove
 * that a number matches the case other sites show under that number.
 */
export const OLL_FULL: readonly AlgorithmDef[] = [
  // Dot (no edges oriented)
  { name: 'OLL 1 (dot)', alg: "R U2 R2 F R F' U2 R' F R F'" },
  { name: 'OLL 2 (dot)', alg: "F R U R' U' F' f R U R' U' f'" },
  { name: 'OLL 3 (dot)', alg: "f R U R' U' f' U' F R U R' U' F'" },
  { name: 'OLL 4 (dot)', alg: "f R U R' U' f' U F R U R' U' F'" },
  { name: 'OLL 17 (dot)', alg: "R U R' U R' F R F' U2 R' F R F'" },
  { name: 'OLL 18 (dot)', alg: "r U R' U R U2 r2 U' R U' R' U2 r" },
  { name: 'OLL 19 (dot)', alg: "r' R U R U R' U' M' R' F R F'" },
  { name: 'OLL 20 (dot)', alg: "r U R' U' M2 U R U' R' U' M'" },
  // Square
  { name: 'OLL 5 (square)', alg: "r' U2 R U R' U r" },
  { name: 'OLL 6 (square)', alg: "r U2 R' U' R U' r'" },
  // Small lightning
  { name: 'OLL 7 (lightning)', alg: "r U R' U R U2 r'" },
  { name: 'OLL 8 (lightning)', alg: "l' U' L U' L' U2 l" },
  { name: 'OLL 11 (lightning)', alg: "r U R' U R' F R F' R U2 r'" },
  { name: 'OLL 12 (lightning)', alg: "F R U R' U' F' U F R U R' U' F'" },
  // Fish
  { name: 'OLL 9 (fish)', alg: "R U R' U' R' F R2 U R' U' F'" },
  { name: 'OLL 10 (fish)', alg: "R U R' U R' F R F' R U2 R'" },
  { name: 'OLL 35 (fish)', alg: "R U2 R2 F R F' R U2 R'" },
  { name: 'OLL 37 (fish)', alg: "F R' F' R U R U' R'" },
  // Knight move
  { name: 'OLL 13 (knight)', alg: "F U R U' R2 F' R U R U' R'" },
  { name: 'OLL 14 (knight)', alg: "R' F R U R' F' R F U' F'" },
  { name: 'OLL 15 (knight)', alg: "r' U' r R' U' R U r' U r" },
  { name: 'OLL 16 (knight)', alg: "r U r' R U R' U' r U' r'" },
  // Corners oriented (OCLL)
  { name: 'OLL 21 (H)', alg: "R U2 R' U' R U R' U' R U' R'" },
  { name: 'OLL 22 (Pi)', alg: "R U2 R2 U' R2 U' R2 U2 R" },
  { name: 'OLL 23 (headlights)', alg: "R2 D' R U2 R' D R U2 R" },
  { name: 'OLL 24 (chameleon)', alg: "r U R' U' r' F R F'" },
  { name: 'OLL 25 (bowtie)', alg: "F' r U R' U' r' F R" },
  { name: 'OLL 26 (antisune)', alg: "R U2 R' U' R U' R'" },
  { name: 'OLL 27 (sune)', alg: "R U R' U R U2 R'" },
  // Corners oriented, edges not
  { name: 'OLL 28 (arrow)', alg: "r U R' U' r' R U R U' R'" },
  { name: 'OLL 57 (H-bar)', alg: "R U R' U' M' U R U' r'" },
  // Awkward
  { name: 'OLL 29 (awkward)', alg: "R U R' U' R U' R' F' U' F R U R'" },
  { name: 'OLL 30 (awkward)', alg: "F R' F R2 U' R' U' R U R' F2" },
  { name: 'OLL 41 (awkward)', alg: "R U R' U R U2 R' F R U R' U' F'" },
  { name: 'OLL 42 (awkward)', alg: "R' U' R U' R' U2 R F R U R' U' F'" },
  // P shape
  { name: 'OLL 31 (P)', alg: "R' U' F U R U' R' F' R" },
  { name: 'OLL 32 (P)', alg: "R U B' U' R' U R B R'" },
  { name: 'OLL 43 (P)', alg: "R' U' F' U F R" },
  { name: 'OLL 44 (P)', alg: "F U R U' R' F'" },
  // T shape
  { name: 'OLL 33 (T)', alg: "R U R' U' R' F R F'" },
  { name: 'OLL 45 (T)', alg: "F R U R' U' F'" },
  // C shape
  { name: 'OLL 34 (C)', alg: "R U R2 U' R' F R U R U' F'" },
  { name: 'OLL 46 (C)', alg: "R' U' R' F R F' U R" },
  // W shape
  { name: 'OLL 36 (W)', alg: "L' U' L U' L' U L U L F' L' F" },
  { name: 'OLL 38 (W)', alg: "R U R' U R U' R' U' R' F R F'" },
  // Big lightning
  { name: 'OLL 39 (lightning)', alg: "L F' L' U' L U F U' L'" },
  { name: 'OLL 40 (lightning)', alg: "R' F R U R' U' F' U R" },
  // L shape
  { name: 'OLL 47 (L)', alg: "R' U' R' F R F' R' F R F' U R" },
  { name: 'OLL 48 (L)', alg: "F R U R' U' R U R' U' F'" },
  { name: 'OLL 49 (L)', alg: "r U' r2 U r2 U r2 U' r" },
  { name: 'OLL 50 (L)', alg: "r' U r2 U' r2 U' r2 U r'" },
  { name: 'OLL 53 (L)', alg: "r' U' R U' R' U R U' R' U2 r" },
  { name: 'OLL 54 (L)', alg: "r U R' U R U' R' U R U2 r'" },
  // Line
  { name: 'OLL 51 (line)', alg: "F U R U' R' U R U' R' F'" },
  { name: 'OLL 52 (line)', alg: "R U R' U R U' B U' B' R'" },
  { name: 'OLL 55 (line)', alg: "R U2 R2 U' R U' R' U2 F R F'" },
  { name: 'OLL 56 (line)', alg: "r' U' r U' R' U R U' R' U R r' U r" },
]
