import type { AlgorithmDef } from './caseTable.ts'

/*
 * Algorithm lists. Only the algorithms live here; the patterns they solve
 * are generated by buildCaseTable. To add a case (for example a full OLL
 * set), add a line. The tests check that the lists cover every last-layer
 * state and that no two entries solve the same case.
 *
 * Algorithms may contain rotations (x y z) and wide/slice moves. A net
 * rotation at the end is undone automatically.
 */

/** 2-look OLL, step 1: orient the edges (make the cross). */
export const OLL_2LOOK_EDGES: readonly AlgorithmDef[] = [
  { name: 'Line', alg: "F R U R' U' F'" },
  { name: 'L-shape', alg: "f R U R' U' f'" },
  { name: 'Dot', alg: "F R U R' U' F' f R U R' U' f'" },
]

/** 2-look OLL, step 2: orient the corners (edges already oriented). */
export const OLL_2LOOK_CORNERS: readonly AlgorithmDef[] = [
  { name: 'Sune', alg: "R U R' U R U2 R'" },
  { name: 'Antisune', alg: "R U2 R' U' R U' R'" },
  { name: 'H', alg: "R U R' U R U' R' U R U2 R'" },
  { name: 'Pi', alg: "R U2 R2 U' R2 U' R2 U2 R" },
  { name: 'Headlights', alg: "R2 D R' U2 R D' R' U2 R'" },
  { name: 'T', alg: "r U R' U' r' F R F'" },
  { name: 'Bowtie', alg: "F' r U R' U' r' F R" },
]

/** 2-look PLL, step 1: permute the corners. */
export const PLL_2LOOK_CORNERS: readonly AlgorithmDef[] = [
  { name: 'Headlights (T-perm)', alg: "R U R' U' R' F R2 U' R' U' R U R' F'" },
  { name: 'Diagonal (Y-perm)', alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
]

/** 2-look PLL, step 2: permute the edges (corners already solved). */
export const PLL_2LOOK_EDGES: readonly AlgorithmDef[] = [
  { name: 'Ua', alg: "M2 U M U2 M' U M2" },
  { name: 'Ub', alg: "M2 U' M U2 M' U' M2" },
  { name: 'H', alg: 'M2 U M2 U2 M2 U M2' },
  { name: 'Z', alg: "M' U M2 U M2 U M' U2 M2" },
]

/** Full PLL: all 21 cases. */
export const PLL_FULL: readonly AlgorithmDef[] = [
  { name: 'Aa', alg: "x R' U R' D2 R U' R' D2 R2 x'" },
  { name: 'Ab', alg: "x R2 D2 R U R' D2 R U' R x'" },
  { name: 'E', alg: "x' R U' R' D R U R' D' R U R' D R U' R' D' x" },
  { name: 'F', alg: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R" },
  { name: 'Ga', alg: "R2 U R' U R' U' R U' R2 U' D R' U R D'" },
  { name: 'Gb', alg: "R' U' R U D' R2 U R' U R U' R U' R2 D" },
  { name: 'Gc', alg: "R2 U' R U' R U R' U R2 U D' R U' R' D" },
  { name: 'Gd', alg: "R U R' U' D R2 U' R U' R' U R' U R2 D'" },
  { name: 'H', alg: 'M2 U M2 U2 M2 U M2' },
  { name: 'Ja', alg: "x R2 F R F' R U2 r' U r U2 x'" },
  { name: 'Jb', alg: "R U R' F' R U R' U' R' F R2 U' R'" },
  { name: 'Na', alg: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'" },
  { name: 'Nb', alg: "R' U R U' R' F' U' F R U R' F R' F' R U' R" },
  { name: 'Ra', alg: "R U' R' U' R U R D R' U' R D' R' U2 R'" },
  { name: 'Rb', alg: "R2 F R U R U' R' F' R U2 R' U2 R" },
  { name: 'T', alg: "R U R' U' R' F R2 U' R' U' R U R' F'" },
  { name: 'Ua', alg: "M2 U M U2 M' U M2" },
  { name: 'Ub', alg: "M2 U' M U2 M' U' M2" },
  { name: 'V', alg: "R' U R' U' y R' F' R2 U' R' U R' F R F" },
  { name: 'Y', alg: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
  { name: 'Z', alg: "M' U M2 U M2 U M' U2 M2" },
]
